apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: paas-api-rolebinding
subjects:
- kind: ServiceAccount
  name: paas-api-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: paas-api-role
  apiGroup: rbac.authorization.k8s.io
