
- name: Install K3s on master
  hosts: k3s_master
  become: true
  tasks:
    - name: Install K3s server
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Get K3s node token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Set fact for node token
      set_fact:
        node_token: "{{ k3s_token.stdout }}"

- name: Join worker nodes
  hosts: k3s_workers
  become: true
  vars:
    master_ip: "{{ hostvars[groups['k3s_master'][0]].ansible_host }}"
    node_token: "{{ hostvars[groups['k3s_master'][0]].node_token }}"
  tasks:
    - name: Join K3s cluster as agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL="https://{{ master_ip }}:6443" K3S_TOKEN="{{ node_token }}" sh -
      args:
        creates: /usr/local/bin/k3s-agent

